INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (1, 9, 'Bueno');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (2, 9, 'Malo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (3, 10, 'Bueno');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (4, 10, 'Malo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (5, 11, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (6, 11, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (7, 12, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (8, 12, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (9, 13, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (10, 13, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (11, 14, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (12, 14, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (13, 15, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (14, 15, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (15, 16, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (16, 16, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (17, 17, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (18, 17, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (19, 18, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (20, 18, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (21, 19, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (22, 19, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (23, 20, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (24, 20, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (25, 21, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (26, 21, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (27, 23, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (28, 23, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (29, 22, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (30, 22, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (31, 24, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (32, 24, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (33, 25, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (34, 25, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (35, 25, 'Regular');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (36, 26, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (37, 26, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (38, 27, 'Mala');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (39, 26, 'Regular');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (40, 27, 'Buena');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (41, 27, 'Regular');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (42, 28, 'Torreón');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (43, 28, 'Gómez Palacio');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (44, 28, 'Lerdo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (45, 28, 'Matamoros');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (46, 31, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (47, 31, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (48, 31, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (49, 31, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (50, 31, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (51, 32, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (52, 32, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (53, 32, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (54, 32, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (55, 32, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (56, 33, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (57, 33, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (58, 33, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (59, 33, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (60, 33, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (61, 34, 'Inseguridd');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (62, 34, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (63, 34, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (64, 34, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (65, 35, 'Inseguridd');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (66, 34, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (67, 35, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (68, 36, 'Inseguridd');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (69, 35, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (70, 35, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (71, 35, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (72, 36, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (73, 37, 'Inseguridd');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (74, 37, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (75, 37, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (76, 36, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (77, 37, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (78, 36, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (79, 37, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (80, 36, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (81, 38, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (82, 38, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (83, 38, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (84, 38, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (85, 38, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (86, 39, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (87, 39, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (88, 39, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (89, 39, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (90, 39, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (91, 40, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (92, 40, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (93, 40, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (94, 40, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (95, 40, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (96, 41, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (97, 41, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (98, 41, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (99, 41, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (100, 41, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (101, 42, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (102, 42, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (103, 42, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (104, 42, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (105, 42, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (106, 43, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (107, 43, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (108, 43, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (109, 43, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (110, 43, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (111, 44, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (112, 44, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (113, 44, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (114, 44, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (115, 44, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (116, 45, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (117, 45, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (118, 45, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (119, 45, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (120, 45, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (121, 45, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (122, 46, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (123, 46, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (124, 46, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (125, 46, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (126, 46, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (127, 46, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (128, 47, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (129, 47, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (130, 47, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (131, 47, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (132, 47, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (133, 47, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (134, 48, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (135, 48, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (136, 48, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (137, 48, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (138, 48, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (139, 48, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (140, 49, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (141, 49, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (142, 49, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (143, 49, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (144, 49, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (145, 49, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (146, 51, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (147, 50, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (148, 51, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (149, 50, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (150, 51, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (151, 50, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (152, 51, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (153, 50, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (154, 51, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (155, 50, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (156, 51, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (157, 50, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (158, 52, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (159, 52, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (160, 52, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (161, 52, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (162, 52, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (163, 52, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (164, 53, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (165, 53, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (166, 53, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (167, 53, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (168, 53, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (169, 53, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (170, 55, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (171, 54, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (172, 55, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (173, 54, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (174, 55, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (175, 54, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (176, 55, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (177, 54, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (178, 55, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (179, 54, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (180, 55, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (181, 54, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (182, 56, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (183, 56, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (184, 56, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (185, 56, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (186, 56, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (187, 56, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (188, 57, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (189, 57, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (190, 57, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (191, 57, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (192, 57, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (193, 57, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (194, 58, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (195, 58, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (196, 59, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (197, 59, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (198, 60, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (199, 60, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (200, 61, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (201, 61, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (202, 62, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (203, 62, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (204, 63, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (205, 63, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (206, 64, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (207, 64, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (208, 73, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (209, 73, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (210, 73, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (211, 73, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (212, 73, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (213, 73, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (214, 74, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (215, 74, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (216, 74, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (217, 74, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (218, 74, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (219, 74, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (220, 75, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (221, 75, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (222, 75, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (223, 75, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (224, 75, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (225, 75, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (226, 76, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (227, 76, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (228, 76, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (229, 76, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (230, 76, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (231, 76, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (232, 77, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (233, 77, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (234, 77, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (235, 77, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (236, 77, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (237, 77, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (238, 78, 'Inseguridad');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (239, 78, 'Desempleo');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (240, 78, 'Corrupción');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (241, 78, 'Baches en calles y avenidas');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (242, 78, 'Fallas en suministro de agua potable');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (243, 78, 'Otro');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (244, 79, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (245, 79, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (246, 80, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (247, 80, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (248, 81, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (249, 81, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (250, 82, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (251, 82, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (252, 83, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (253, 83, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (254, 84, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (255, 84, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (256, 85, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (257, 85, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (258, 86, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (259, 86, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (260, 87, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (261, 88, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (262, 87, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (263, 89, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (264, 88, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (265, 89, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (266, 90, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (267, 90, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (268, 91, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (269, 91, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (270, 92, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (271, 93, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (272, 92, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (273, 93, 'No');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (274, 94, 'Sí');
INSERT INTO webandpr_vvTjz1Bk.app_answers (id, question_id, title) VALUES (275, 94, 'No');