INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (1, 1, 'first_name', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (2, 1, 'last_name', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (3, 1, 'nickname', 'admin');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (4, 1, 'description', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (5, 1, 'rich_editing', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (6, 1, 'comment_shortcuts', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (7, 1, 'admin_color', 'fresh');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (8, 1, 'use_ssl', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (9, 1, 'aim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (10, 1, 'yim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (11, 1, 'jabber', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (12, 1, 'w47fa_capabilities', 'a:1:{s:13:"administrator";s:1:"1";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (13, 1, 'w47fa_user_level', '10');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (14, 1, 'session_tokens', 'a:1:{s:64:"7db4e0623fec29122838052d05298bbe996ecd507006ef4b6a5e729653cda0b0";a:4:{s:10:"expiration";i:1588382210;s:2:"ip";s:14:"177.228.170.88";s:2:"ua";s:131:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 Edg/81.0.416.68";s:5:"login";i:1588209410;}}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (90, 1, 'last_login_time', '2019-04-07 05:10:27');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (92, 1, 'metaboxhidden_carousels', 'a:3:{i:0;s:19:"sb_divi_fe_meta_box";i:1;s:21:"the_grid_item_formats";i:2;s:7:"slugdiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (15, 1, 'w47fa_dashboard_quick_press_last_post_id', '6988');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (16, 1, 'community-events-location', 'a:1:{s:2:"ip";s:13:"177.228.170.0";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (17, 1, 'w47fa_user-settings', 'libraryContent=browse&editor=tinymce&imgsize=full&urlbutton=none&align=left&mfold=o&advImgDetails=show&editor_expand=off&ed_size=555');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (18, 1, 'w47fa_user-settings-time', '1575062910');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (19, 1, 'default_password_nag', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (20, 2, 'nickname', 'observatorio_lag');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (21, 2, 'first_name', 'Observatorio');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (22, 2, 'last_name', 'de La Laguna');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (23, 2, 'description', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (24, 2, 'rich_editing', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (25, 2, 'syntax_highlighting', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (26, 2, 'comment_shortcuts', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (27, 2, 'admin_color', 'fresh');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (28, 2, 'use_ssl', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (29, 2, 'show_admin_bar_front', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (30, 2, 'locale', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (31, 2, 'w47fa_capabilities', 'a:1:{s:6:"author";b:1;}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (32, 2, 'w47fa_user_level', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (33, 2, 'dismissed_wp_pointers', 'wpmudcs1');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (34, 1, 'meta-box-order_post', 'a:3:{s:4:"side";s:130:"et_settings_meta_box,submitdiv,authordiv,postimagediv,tagsdiv-post_tag,categorydiv,formatdiv,sb_divi_fe_meta_box,customsidebars-mb";s:6:"normal";s:115:"pods-meta-mas-campos,wpseo_meta,the_grid_item_formats,postexcerpt,trackbacksdiv,postcustom,commentstatusdiv,slugdiv";s:8:"advanced";s:0:"";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (35, 1, 'screen_layout_post', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (36, 1, 'closedpostboxes_post', 'a:9:{i:0;s:20:"et_settings_meta_box";i:1;s:19:"sb_divi_fe_meta_box";i:2;s:17:"customsidebars-mb";i:3;s:20:"pods-meta-mas-campos";i:4;s:21:"the_grid_item_formats";i:5;s:11:"postexcerpt";i:6;s:13:"trackbacksdiv";i:7;s:10:"postcustom";i:8;s:7:"slugdiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (37, 1, 'metaboxhidden_post', 'a:7:{i:0;s:20:"et_settings_meta_box";i:1;s:19:"sb_divi_fe_meta_box";i:2;s:17:"customsidebars-mb";i:3;s:13:"trackbacksdiv";i:4;s:10:"postcustom";i:5;s:16:"commentstatusdiv";i:6;s:7:"slugdiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (38, 2, 'aim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (39, 2, 'yim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (40, 2, 'jabber', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (41, 1, 'caldera_forms_activation_ignore_notice', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (42, 1, 'show_per_page', '25');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (43, 1, 'orderby', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (58, 2, 'zay5_media_library_mode', 'list');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (59, 1, 'closedpostboxes_page', 'a:3:{i:0;s:10:"wpseo_meta";i:1;s:21:"the_grid_item_formats";i:2;s:10:"postcustom";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (45, 2, 'w47fa_dashboard_quick_press_last_post_id', '7002');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (46, 2, 'community-events-location', 'a:1:{s:2:"ip";s:13:"189.145.209.0";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (47, 2, 'closedpostboxes_post', 'a:4:{i:0;s:9:"formatdiv";i:1;s:10:"wpseo_meta";i:2;s:21:"the_grid_item_formats";i:3;s:20:"pods-meta-mas-campos";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (48, 2, 'metaboxhidden_post', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (217, 2, 'enable_custom_fields', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (49, 2, 'meta-box-order_post', 'a:3:{s:4:"side";s:81:"submitdiv,postimagediv,formatdiv,categorydiv,tagsdiv-post_tag,sb_divi_fe_meta_box";s:6:"normal";s:115:"wpseo_meta,the_grid_item_formats,postexcerpt,trackbacksdiv,postcustom,commentstatusdiv,slugdiv,pods-meta-mas-campos";s:8:"advanced";s:0:"";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (50, 2, 'screen_layout_post', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (51, 2, 'twitter', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (52, 2, 'facebook', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (53, 2, 'google_plus', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (54, 2, 'w47fa_user-settings', 'libraryContent=browse&editor=tinymce&imgsize=full&advImgDetails=show&post_dfw=off');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (55, 2, 'w47fa_user-settings-time', '1571351005');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (56, 1, 'closedpostboxes_attachment', 'a:1:{i:0;s:21:"the_grid_item_formats";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (57, 1, 'metaboxhidden_attachment', 'a:6:{i:0;s:19:"sb_divi_fe_meta_box";i:1;s:21:"the_grid_item_formats";i:2;s:16:"commentstatusdiv";i:3;s:11:"commentsdiv";i:4;s:7:"slugdiv";i:5;s:9:"authordiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (60, 1, 'metaboxhidden_page', 'a:1:{i:0;s:21:"the_grid_item_formats";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (61, 1, 'bdpclosedbdpboxes_designer_settings', 'a:1:{i:0;s:9:"bdpsocial";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (62, 1, 'meta-box-order_page', 'a:3:{s:4:"side";s:106:"et_settings_meta_box,postimagediv,submitdiv,pageparentdiv,sb_divi_fe_meta_box,customsidebars-mb,secciondiv";s:6:"normal";s:151:"et_pb_layout,the_grid_item_formats,pods-meta-mas-campos,revisionsdiv,postexcerpt,postcustom,commentstatusdiv,commentsdiv,slugdiv,authordiv,main_metabox";s:8:"advanced";s:0:"";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (63, 1, 'screen_layout_page', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (64, 1, 'managenav-menuscolumnshidden', 'a:4:{i:0;s:15:"title-attribute";i:1;s:11:"css-classes";i:2;s:3:"xfn";i:3;s:11:"description";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (65, 1, 'metaboxhidden_nav-menus', 'a:7:{i:0;s:21:"add-post-type-project";i:1;s:12:"add-post_tag";i:2;s:15:"add-post_format";i:3;s:20:"add-project_category";i:4;s:15:"add-project_tag";i:5;s:18:"add-media-category";i:6;s:13:"add-media-tag";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (66, 1, 'dismissed_wp_pointers', 'msp_1_4_3__25samples,master_1_0_view_help,wpmudcs1,text_widget_custom_html,text_widget_paste_html,wp496_privacy');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (67, 1, 'nav_menu_recently_edited', '188');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (68, 1, 'closedpostboxes_et_pb_layout', 'a:2:{i:0;s:18:"layout_categorydiv";i:1;s:12:"revisionsdiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (69, 1, 'metaboxhidden_et_pb_layout', 'a:6:{i:0;s:18:"layout_categorydiv";i:1;s:11:"postexcerpt";i:2;s:12:"postimagediv";i:3;s:21:"the_grid_item_formats";i:4;s:12:"revisionsdiv";i:5;s:7:"slugdiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (70, 1, 'closedpostboxes_w4pl', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (71, 1, 'metaboxhidden_w4pl', 'a:5:{i:0;s:18:"w4pl_news_meta_box";i:1;s:17:"customsidebars-mb";i:2;s:19:"sb_divi_fe_meta_box";i:3;s:21:"the_grid_item_formats";i:4;s:7:"slugdiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (137, 1, 'ac_preferences_check-addon-available', 'a:1:{s:14:"dismiss-notice";s:1:"1";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (73, 1, 'zay5_ac_preferences_settings', 'a:1:{s:11:"list_screen";s:4:"post";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (74, 1, 'closedpostboxes_ditty_news_ticker', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (75, 1, 'metaboxhidden_ditty_news_ticker', 'a:6:{i:0;s:17:"customsidebars-mb";i:1;s:19:"sb_divi_fe_meta_box";i:2;s:21:"the_grid_item_formats";i:3;s:7:"slugdiv";i:4;s:9:"authordiv";i:5;s:21:"mymetabox_revslider_0";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (76, 1, 'closedpostboxes_divi_bars', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (77, 1, 'metaboxhidden_divi_bars', 'a:7:{i:0;s:17:"customsidebars-mb";i:1;s:19:"sb_divi_fe_meta_box";i:2;s:12:"et_pb_layout";i:3;s:21:"the_grid_item_formats";i:4;s:7:"slugdiv";i:5;s:9:"authordiv";i:6;s:21:"mymetabox_revslider_0";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (78, 1, 'syntax_highlighting', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (79, 1, 'show_admin_bar_front', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (80, 1, 'locale', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (81, 1, 'twitter', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (82, 1, 'facebook', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (83, 1, 'google_plus', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (84, 1, 'cf_pointer_add_element', 'a:1:{i:0;N;}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (86, 1, 'zay5_media_library_mode', 'list');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (88, 1, 'closedpostboxes_divi_overlay', 'a:3:{i:0;s:17:"customsidebars-mb";i:1;s:19:"sb_divi_fe_meta_box";i:2;s:21:"the_grid_item_formats";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (89, 1, 'metaboxhidden_divi_overlay', 'a:4:{i:0;s:17:"customsidebars-mb";i:1;s:19:"sb_divi_fe_meta_box";i:2;s:21:"the_grid_item_formats";i:3;s:9:"authordiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (91, 1, 'closedpostboxes_carousels', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (142, 2, 'session_tokens', 'a:1:{s:64:"134af5d6649a69d84339e1764c5b7e0cffbe0453773262855f7193805bfe29f1";a:4:{s:10:"expiration";i:1589913680;s:2:"ip";s:14:"189.145.209.12";s:2:"ua";s:115:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36";s:5:"login";i:1588704080;}}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (115, 1, 'closedpostboxes_content_block', 'a:1:{i:0;s:21:"the_grid_item_formats";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (116, 1, 'metaboxhidden_content_block', 'a:2:{i:0;s:7:"slugdiv";i:1;s:9:"authordiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (94, 3, 'nickname', 'observatorio');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (95, 3, 'first_name', 'Revision');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (96, 3, 'last_name', 'Observatorio');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (97, 3, 'description', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (98, 3, 'rich_editing', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (99, 3, 'syntax_highlighting', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (100, 3, 'comment_shortcuts', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (101, 3, 'admin_color', 'fresh');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (102, 3, 'use_ssl', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (103, 3, 'show_admin_bar_front', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (104, 3, 'locale', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (105, 3, 'w47fa_capabilities', 'a:1:{s:10:"subscriber";b:1;}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (106, 3, 'w47fa_user_level', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (107, 3, 'dismissed_wp_pointers', 'wp496_privacy');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (108, 3, 'aim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (109, 3, 'yim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (110, 3, 'jabber', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (111, 3, 'twitter', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (112, 3, 'facebook', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (113, 3, 'google_plus', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (114, 3, 'session_tokens', 'a:6:{s:64:"f935cb50850c947ef6bdf8f99ec164b72aeee95c45dbd80d166f52a44d46c01d";a:4:{s:10:"expiration";i:1530026242;s:2:"ip";s:14:"177.228.182.72";s:2:"ua";s:114:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36";s:5:"login";i:1528816642;}s:64:"43a1fa16c89b27e39854ffc51deeb18a10d38517efbb6362ff4f7e5f2b3f0c98";a:4:{s:10:"expiration";i:1530026590;s:2:"ip";s:14:"177.228.182.72";s:2:"ua";s:114:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36";s:5:"login";i:1528816990;}s:64:"f293e0a482a60caa44dec01184b9da189b01461ccfcfb7de4ff153493c8451c5";a:4:{s:10:"expiration";i:1530035751;s:2:"ip";s:15:"189.244.173.212";s:2:"ua";s:120:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36";s:5:"login";i:1528826151;}s:64:"7ef2ba3ed73dc7c2200bb544d176213c41cde953284d9ca85024a4cb742407d6";a:4:{s:10:"expiration";i:1530057986;s:2:"ip";s:14:"200.92.216.146";s:2:"ua";s:121:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36";s:5:"login";i:1528848386;}s:64:"6d1872de8feef1f88d0dde7cd771aef9a3d44f20e4c3ba367d2b21080a5697fa";a:4:{s:10:"expiration";i:1530057988;s:2:"ip";s:14:"200.92.216.146";s:2:"ua";s:121:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36";s:5:"login";i:1528848388;}s:64:"0e39b540a52c398bc433c78971bba588b766d3510837bb391927b6873f769d06";a:4:{s:10:"expiration";i:1530118939;s:2:"ip";s:14:"200.92.216.146";s:2:"ua";s:121:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36";s:5:"login";i:1528909339;}}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (119, 1, 'pcsl_ac_preferences_settings', 'a:1:{s:11:"list_screen";s:4:"post";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (120, 2, '_yoast_wpseo_profile_updated', '1529963626');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (121, 1, '_yoast_wpseo_profile_updated', '1564197601');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (122, 2, 'wpseo_title', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (123, 2, 'wpseo_metadesc', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (124, 2, 'wpseo_noindex_author', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (125, 2, 'wpseo_content_analysis_disable', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (126, 2, 'wpseo_keyword_analysis_disable', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (127, 2, 'googleplus', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (128, 1, 'closedpostboxes_los-medios', 'a:1:{i:0;s:11:"postexcerpt";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (129, 1, 'metaboxhidden_los-medios', 'a:7:{i:0;s:11:"categorydiv";i:1;s:16:"tagsdiv-post_tag";i:2;s:17:"customsidebars-mb";i:3;s:19:"sb_divi_fe_meta_box";i:4;s:21:"the_grid_item_formats";i:5;s:11:"postexcerpt";i:6;s:7:"slugdiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (130, 1, 'meta-box-order_los-medios', 'a:3:{s:4:"side";s:96:"submitdiv,categorydiv,tagsdiv-post_tag,customsidebars-mb,sb_divi_fe_meta_box,formatdiv,authordiv";s:6:"normal";s:62:"the_grid_item_formats,pods-meta-mas-campos,postexcerpt,slugdiv";s:8:"advanced";s:0:"";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (131, 1, 'screen_layout_los-medios', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (132, 1, 'closedpostboxes_popup', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (133, 1, 'metaboxhidden_popup', 'a:5:{i:0;s:17:"customsidebars-mb";i:1;s:19:"sb_divi_fe_meta_box";i:2;s:21:"the_grid_item_formats";i:3;s:7:"slugdiv";i:4;s:9:"authordiv";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (134, 1, '_pum_reviews_dismissed_triggers', 'a:2:{s:10:"open_count";s:2:"20";s:14:"time_installed";s:2:"30";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (135, 1, '_pum_reviews_last_dismissed', '2018-09-28 19:32:49');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (136, 1, 'ac_preferences_check-review', 'a:2:{s:14:"dismiss-review";s:1:"1";s:18:"first-login-review";s:10:"1526327790";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (138, 2, 'last_login_time', '2018-08-29 12:06:46');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (139, 2, '_pum_reviews_dismissed_triggers', 'a:1:{s:10:"open_count";s:2:"10";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (140, 2, '_pum_reviews_last_dismissed', '2018-08-02 10:51:17');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (147, 1, 'show_try_gutenberg_panel', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (148, 1, 'show_welcome_panel', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (167, 1, 'pcsl_yoast_notifications', 'a:3:{i:0;a:2:{s:7:"message";s:1201:"Hemos observado que has estado usando Yoast SEO desde hace algún tiempo; ¡esperamos que te guste! ¡Nos encantaría que pudieras <a href="https://yoa.st/rate-yoast-seo?php_version=5.6.21&platform=wordpress&platform_version=5.0.2&software=free&software_version=9.4&role=administrator&days_active=205">dejarnos una valoración de 5 estrellas en WordPress.org</a>!

Si estás teniendo problemas, <a href="https://yoa.st/bugreport?php_version=5.6.21&platform=wordpress&platform_version=5.0.2&software=free&software_version=9.4&role=administrator&days_active=205">por favor, envía un informe de fallos</a> y haremos todo lo posible para ayudarte.

Por cierto, ¿sabías que también tenemos un <a href=''https://yoa.st/premium-notification?php_version=5.6.21&platform=wordpress&platform_version=5.0.2&software=free&software_version=9.4&role=administrator&days_active=205''>plugin Premium</a>? Ofrece funcionalidades avanzadas, como un gestor de redirecciones y compatibilidad con múltiples frases clave. También incluye soporte personal 24/7.

<a class="button" href="http://observatoriodelalaguna.org.mx/wp-admin/?page=wpseo_dashboard&yoast_dismiss=upsell">Por favor, no me muestres más este aviso</a>";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:19:"wpseo-upsell-notice";s:5:"nonce";N;s:8:"priority";d:0.80000000000000004;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}i:1;a:2:{s:7:"message";s:190:"No te pierdas los errores de rastreo. <a href="http://observatoriodelalaguna.org.mx/wp-admin/admin.php?page=wpseo_search_console&tab=settings">Conecta aquí con la Google Search Console</a>.";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:17:"wpseo-dismiss-gsc";s:5:"nonce";N;s:8:"priority";d:0.5;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}i:2;a:2:{s:7:"message";s:464:"¡Nos encantaría que probaras nuestro nuevo y mejorado análisis de Yoast SEO! Usa el botón de la <a href="#top#features" onclick="jQuery(''#features-tab'').click()">pestaña de características</a> en tus ajustes de Yoast SEO. <a href="https://yoa.st/recalibration-beta-notice?php_version=5.6.21&platform=wordpress&platform_version=5.0.2&software=free&software_version=9.4&role=administrator&days_active=205" target="_blank">Lee más sobre el nuevo análisis</a>.";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:37:"wpseo-recalibration-meta-notification";s:5:"nonce";N;s:8:"priority";i:1;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (168, 1, 'mU2Pz_yoast_notifications', 'a:3:{i:0;a:2:{s:7:"message";s:1201:"Hemos observado que has estado usando Yoast SEO desde hace algún tiempo; ¡esperamos que te guste! ¡Nos encantaría que pudieras <a href="https://yoa.st/rate-yoast-seo?php_version=7.0.33&platform=wordpress&platform_version=5.0.3&software=free&software_version=9.4&role=administrator&days_active=206">dejarnos una valoración de 5 estrellas en WordPress.org</a>!

Si estás teniendo problemas, <a href="https://yoa.st/bugreport?php_version=7.0.33&platform=wordpress&platform_version=5.0.3&software=free&software_version=9.4&role=administrator&days_active=206">por favor, envía un informe de fallos</a> y haremos todo lo posible para ayudarte.

Por cierto, ¿sabías que también tenemos un <a href=''https://yoa.st/premium-notification?php_version=7.0.33&platform=wordpress&platform_version=5.0.3&software=free&software_version=9.4&role=administrator&days_active=206''>plugin Premium</a>? Ofrece funcionalidades avanzadas, como un gestor de redirecciones y compatibilidad con múltiples frases clave. También incluye soporte personal 24/7.

<a class="button" href="https://observatorio.webandpress.com/wp-admin/?page=wpseo_dashboard&yoast_dismiss=upsell">Por favor, no me muestres más este aviso</a>";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:19:"wpseo-upsell-notice";s:5:"nonce";N;s:8:"priority";d:0.80000000000000004;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}i:1;a:2:{s:7:"message";s:190:"No te pierdas los errores de rastreo. <a href="https://observatorio.webandpress.com/wp-admin/admin.php?page=wpseo_search_console&tab=settings">Conecta aquí con la Google Search Console</a>.";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:17:"wpseo-dismiss-gsc";s:5:"nonce";N;s:8:"priority";d:0.5;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}i:2;a:2:{s:7:"message";s:464:"¡Nos encantaría que probaras nuestro nuevo y mejorado análisis de Yoast SEO! Usa el botón de la <a href="#top#features" onclick="jQuery(''#features-tab'').click()">pestaña de características</a> en tus ajustes de Yoast SEO. <a href="https://yoa.st/recalibration-beta-notice?php_version=7.0.33&platform=wordpress&platform_version=5.0.3&software=free&software_version=9.4&role=administrator&days_active=206" target="_blank">Lee más sobre el nuevo análisis</a>.";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:37:"wpseo-recalibration-meta-notification";s:5:"nonce";N;s:8:"priority";i:1;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (224, 1, 'FJ721Eb_yoast_notifications', 'a:2:{i:0;a:2:{s:7:"message";s:1211:"Hemos observado que has estado usando Yoast SEO desde hace algún tiempo; ¡esperamos que te guste! ¡Nos encantaría que pudieras <a href="https://yoa.st/rate-yoast-seo?php_version=7.0.33&platform=wordpress&platform_version=5.1.1&software=free&software_version=10.0.1&role=administrator&days_active=284">dejarnos una valoración de 5 estrellas en WordPress.org</a>!

Si estás teniendo problemas, <a href="https://yoa.st/bugreport?php_version=7.0.33&platform=wordpress&platform_version=5.1.1&software=free&software_version=10.0.1&role=administrator&days_active=284">por favor, envía un informe de fallos</a> y haremos todo lo posible para ayudarte.

Por cierto, ¿sabías que también tenemos un <a href=''https://yoa.st/premium-notification?php_version=7.0.33&platform=wordpress&platform_version=5.1.1&software=free&software_version=10.0.1&role=administrator&days_active=284''>plugin Premium</a>? Ofrece funcionalidades avanzadas, como un gestor de redirecciones y compatibilidad con múltiples frases clave. También incluye soporte personal 24/7.

<a class="button" href="https://observatoriodelalaguna.org.mx/wp-admin/?page=wpseo_dashboard&yoast_dismiss=upsell">Por favor, no me muestres más este aviso</a>";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:19:"wpseo-upsell-notice";s:5:"nonce";N;s:8:"priority";d:0.80000000000000004;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}i:1;a:2:{s:7:"message";s:191:"No te pierdas los errores de rastreo. <a href="https://observatoriodelalaguna.org.mx/wp-admin/admin.php?page=wpseo_search_console&tab=settings">Conecta aquí con la Google Search Console</a>.";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:17:"wpseo-dismiss-gsc";s:5:"nonce";N;s:8:"priority";d:0.5;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (170, 4, 'nickname', 'marco_user');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (171, 4, 'first_name', 'Marco Antonio');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (172, 4, 'last_name', 'Zamarripa González');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (173, 4, 'description', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (174, 4, 'rich_editing', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (175, 4, 'syntax_highlighting', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (176, 4, 'comment_shortcuts', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (177, 4, 'admin_color', 'fresh');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (178, 4, 'use_ssl', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (179, 4, 'show_admin_bar_front', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (180, 4, 'locale', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (181, 4, 'w47fa_capabilities', 'a:1:{s:6:"author";b:1;}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (182, 4, 'w47fa_user_level', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (183, 4, '_yoast_wpseo_profile_updated', '1547946366');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (184, 4, 'dismissed_wp_pointers', 'wp496_privacy');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (185, 5, 'nickname', 'david_user');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (186, 5, 'first_name', 'David');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (187, 5, 'last_name', 'Ruelas Sarmiento');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (188, 5, 'description', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (189, 5, 'rich_editing', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (190, 5, 'syntax_highlighting', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (191, 5, 'comment_shortcuts', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (192, 5, 'admin_color', 'fresh');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (193, 5, 'use_ssl', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (194, 5, 'show_admin_bar_front', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (195, 5, 'locale', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (196, 5, 'w47fa_capabilities', 'a:1:{s:6:"author";b:1;}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (197, 5, 'w47fa_user_level', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (198, 5, '_yoast_wpseo_profile_updated', '1547948535');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (199, 5, 'dismissed_wp_pointers', 'wp496_privacy');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (200, 6, 'nickname', 'luis_user');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (201, 6, 'first_name', 'Luis Alfredo');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (202, 6, 'last_name', 'Medina López');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (203, 6, 'description', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (204, 6, 'rich_editing', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (205, 6, 'syntax_highlighting', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (206, 6, 'comment_shortcuts', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (207, 6, 'admin_color', 'fresh');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (208, 6, 'use_ssl', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (209, 6, 'show_admin_bar_front', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (210, 6, 'locale', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (211, 6, 'w47fa_capabilities', 'a:1:{s:6:"author";b:1;}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (212, 6, 'w47fa_user_level', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (213, 6, '_yoast_wpseo_profile_updated', '1547949713');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (214, 6, 'dismissed_wp_pointers', 'wp496_privacy');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (215, 1, 'meta-box-order_et_pb_layout', 'a:3:{s:4:"side";s:53:"submitdiv,layout_categorydiv,postexcerpt,postimagediv";s:6:"normal";s:55:"et_pb_layout,the_grid_item_formats,revisionsdiv,slugdiv";s:8:"advanced";s:0:"";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (216, 1, 'screen_layout_et_pb_layout', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (218, 1, '_pum_dismissed_alerts', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (219, 2, '_pum_dismissed_alerts', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (324, 1, 'ob_yoast_notifications', 'a:2:{i:0;a:2:{s:7:"message";s:1208:"Hemos observado que has estado usando Yoast SEO desde hace algún tiempo; ¡esperamos que te guste! ¡Nos encantaría que pudieras <a href="https://yoa.st/rate-yoast-seo?php_version=5.6.21&platform=wordpress&platform_version=5.1.1&software=free&software_version=10.0.1&role=administrator&days_active=285">dejarnos una valoración de 5 estrellas en WordPress.org</a>!

Si estás teniendo problemas, <a href="https://yoa.st/bugreport?php_version=5.6.21&platform=wordpress&platform_version=5.1.1&software=free&software_version=10.0.1&role=administrator&days_active=285">por favor, envía un informe de fallos</a> y haremos todo lo posible para ayudarte.

Por cierto, ¿sabías que también tenemos un <a href=''https://yoa.st/premium-notification?php_version=5.6.21&platform=wordpress&platform_version=5.1.1&software=free&software_version=10.0.1&role=administrator&days_active=285''>plugin Premium</a>? Ofrece funcionalidades avanzadas, como un gestor de redirecciones y compatibilidad con múltiples frases clave. También incluye soporte personal 24/7.

<a class="button" href="http://observatorio.cadilag.com.mx/wp-admin/?page=wpseo_dashboard&yoast_dismiss=upsell">Por favor, no me muestres más este aviso</a>";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:19:"wpseo-upsell-notice";s:5:"nonce";N;s:8:"priority";d:0.80000000000000004;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}i:1;a:2:{s:7:"message";s:188:"No te pierdas los errores de rastreo. <a href="http://observatorio.cadilag.com.mx/wp-admin/admin.php?page=wpseo_search_console&tab=settings">Conecta aquí con la Google Search Console</a>.";s:7:"options";a:9:{s:4:"type";s:7:"warning";s:2:"id";s:17:"wpseo-dismiss-gsc";s:5:"nonce";N;s:8:"priority";d:0.5;s:9:"data_json";a:0:{}s:13:"dismissal_key";N;s:12:"capabilities";s:20:"wpseo_manage_options";s:16:"capability_check";s:3:"all";s:14:"yoast_branding";b:0;}}}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (391, 1, 'closedpostboxes_nav-menus', 'a:0:{}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (452, 11, 'nickname', 'grupo_admin');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (453, 11, 'first_name', 'Admin Grupo');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (454, 11, 'last_name', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (455, 11, 'description', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (456, 11, 'rich_editing', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (457, 11, 'syntax_highlighting', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (458, 11, 'comment_shortcuts', 'false');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (459, 11, 'admin_color', 'fresh');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (460, 11, 'use_ssl', '0');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (461, 11, 'show_admin_bar_front', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (462, 11, 'locale', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (463, 11, 'w47fa_capabilities', 'a:1:{s:12:"author_admin";b:1;}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (464, 11, 'w47fa_user_level', '2');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (465, 11, '_yoast_wpseo_profile_updated', '1564197728');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (466, 11, 'dismissed_wp_pointers', 'plugin_editor_notice');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (467, 11, 'wpseo_title', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (468, 11, 'wpseo_metadesc', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (469, 11, 'wpseo_noindex_author', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (470, 11, 'wpseo_content_analysis_disable', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (471, 11, 'wpseo_keyword_analysis_disable', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (472, 11, 'aim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (473, 11, 'yim', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (474, 11, 'jabber', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (475, 11, 'twitter', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (476, 11, 'facebook', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (477, 11, 'google_plus', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (478, 11, 'instagram', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (479, 11, 'linkedin', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (480, 11, 'myspace', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (481, 11, 'pinterest', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (482, 11, 'soundcloud', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (483, 11, 'tumblr', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (484, 11, 'youtube', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (485, 11, 'wikipedia', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (487, 11, 'caldera_forms_activation_ignore_notice', 'true');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (488, 11, 'w47fa_dashboard_quick_press_last_post_id', '6158');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (489, 11, 'community-events-location', 'a:1:{s:2:"ip";s:11:"189.244.5.0";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (503, 1, 'wpseo_title', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (504, 1, 'wpseo_metadesc', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (505, 1, 'wpseo_noindex_author', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (506, 1, 'wpseo_content_analysis_disable', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (507, 1, 'wpseo_keyword_analysis_disable', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (508, 1, 'instagram', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (509, 1, 'linkedin', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (510, 1, 'myspace', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (511, 1, 'pinterest', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (512, 1, 'soundcloud', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (513, 1, 'tumblr', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (514, 1, 'youtube', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (515, 1, 'wikipedia', '');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (522, 1, 'closedpostboxes__pods_template', 'a:2:{i:0;s:27:"pods-meta-restringir-acceso";i:1;s:21:"the_grid_item_formats";}');
INSERT INTO webandpr_vvTjz1Bk.w47fa_usermeta (umeta_id, user_id, meta_key, meta_value) VALUES (523, 1, 'metaboxhidden__pods_template', 'a:2:{i:0;s:7:"slugdiv";i:1;s:9:"authordiv";}');