INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (1, 41, 27, 5, '41');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (2, 45, 28, 5, '45');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (3, 38, 27, 5, '38');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (4, 42, 28, 5, '42');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (5, 0, 27, 5, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (6, 0, 28, 5, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (7, 35000, 30, 5, '35000');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (8, 106, 43, 11, '106');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (9, 108, 43, 11, '108');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (10, 108, 43, 11, '108');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (11, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (12, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (13, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (14, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (15, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (16, 243, 78, 17, '243');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (17, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (18, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (19, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (20, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (21, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (22, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (23, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (24, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (25, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (26, 0, 78, 17, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (27, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (28, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (29, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (30, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (31, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (32, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (33, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (34, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (35, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (36, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (37, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (38, 243, 78, 17, '243');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (39, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (40, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (41, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (42, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (43, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (44, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (45, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (46, 243, 78, 17, '243');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (47, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (48, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (49, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (50, 0, 78, 17, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (51, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (52, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (53, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (54, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (55, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (56, 0, 78, 17, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (57, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (58, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (59, 243, 78, 17, '243');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (60, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (61, 248, 81, 18, '248');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (62, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (63, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (64, 0, 98, 20, 'Prueba 1');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (65, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (66, 0, 98, 20, 'David Ruelas');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (67, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (68, 0, 98, 20, 'Talia peñalosa');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (69, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (70, 0, 98, 20, 'Beto Rosales ');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (71, 269, 91, 20, '269');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (72, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (73, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (74, 0, 98, 20, 'Todos... Nacho García ');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (75, 269, 91, 20, '269');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (76, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (77, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (78, 0, 98, 20, 'José Ignacio Garcia');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (79, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (80, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (81, 0, 78, 17, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (82, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (83, 0, 98, 20, 'Chaquetero Corona ');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (84, 0, 78, 17, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (85, 269, 91, 20, '269');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (86, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (87, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (88, 0, 98, 20, 'Nacho Corona');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (89, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (90, 0, 98, 20, 'José Ignacio García Carrillo, José Ignacio Corona, José Antonio Gutierrez Jardón, Alberto Rosales, Lucia Jacobo, Ana Ma. Betancourt, ');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (91, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (92, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (93, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (94, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (95, 238, 78, 17, '238');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (96, 0, 91, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (97, 0, 98, 20, 'Corona ');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (98, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (99, 241, 78, 17, '241');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (100, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (101, 0, 98, 20, 'Ana Betancourt');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (102, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (103, 0, 91, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (104, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (105, 0, 91, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (106, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (107, 242, 78, 17, '242');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (108, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (109, 0, 98, 20, 'Alberto Rosales');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (110, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (111, 0, 91, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (112, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (113, 0, 78, 17, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (114, 0, 91, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (115, 0, 98, 20, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (116, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (117, 0, 98, 20, 'Ignacio Corona');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (118, 239, 78, 17, '239');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (119, 0, 78, 17, '*Selecciona una respuesta');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (120, 268, 91, 20, '268');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (121, 0, 98, 20, 'Jesús Javier Gómez Ledezma');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (122, 240, 78, 17, '240');
INSERT INTO webandpr_vvTjz1Bk.app_question_answer (id, answer_id, question_id, survey_id, other) VALUES (123, 242, 78, 17, '242');