INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (1, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (2, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (3, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (4, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (5, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (6, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (7, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (8, 0, '', '');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (9, 3, '¿Cómo consideras el estado actual de la economía en la Laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (10, 3, '¿Cómo consideras el estado actual de la economía en la Laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (11, 3, 'A ver si así', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (12, 3, 'asd?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (13, 3, 'asd?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (14, 0, 'ddddd?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (15, 3, 'ddddd?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (16, 3, 'fffff?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (17, 3, 'dddddd?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (18, 3, '¿Cómo consideras la economía en la laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (19, 0, '¿Cómo consideras la economía en la laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (20, 0, '¿Cómo consideras la economía en la laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (21, 0, '¿Cómo consideras la economía en la laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (22, 0, '¿Cómo consideras la economía en la laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (23, 0, '¿Cómo consideras la economía en la laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (24, 4, '¿Cómo consideras la economía en la laguna?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (25, 0, '¿Cómo consideras la economía en la laguna?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (26, 0, '¿Cómo consideras la economía en la laguna?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (27, 5, '¿Cómo consideras la economía en la laguna?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (28, 5, '¿Dónde reside?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (29, 0, 'Código Postal', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (30, 5, 'Código Postal', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (31, 9, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (32, 0, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (33, 9, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (34, 9, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (35, 0, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (36, 10, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (37, 9, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (38, 0, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (39, 9, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (40, 9, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (41, 10, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (42, 0, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (43, 11, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (44, 0, '¿Cuál considera usted son las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (45, 11, '¿Cuál considera usted es las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (46, 0, '¿Cuál considera usted es las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (47, 0, '¿Cuál considera usted es las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (48, 0, '¿Cuál considera usted es las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (49, 12, '¿Cuál considera usted es las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (50, 0, '¿Cuál considera usted es las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (51, 11, '¿Cuál considera usted es las problemáticas mas importantes de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (52, 11, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (53, 12, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (54, 0, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (55, 12, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (56, 0, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (57, 13, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (58, 0, '1', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (59, 0, '1', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (60, 13, '1', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (61, 12, '1', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (62, 12, '1', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (63, 11, '1', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (64, 14, '1', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (65, 0, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (66, 13, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (67, 15, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (68, 13, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (69, 0, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (70, 13, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (71, 13, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (72, 15, '521845', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (73, 0, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (74, 13, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (75, 13, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (76, 15, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (77, 16, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (78, 17, '¿Cuál considera usted es la problemática mas importante de su ciudad?', 'MULTI_CHOICE');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (79, 0, ' ¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (80, 0, ' ¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (81, 18, ' ¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (82, 0, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (83, 18, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (84, 19, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (85, 0, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (86, 0, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (87, 18, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (88, 19, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (89, 0, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR  DEL MUNICIPIO DE TORREÓN? ', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (90, 0, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (91, 20, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (92, 19, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (93, 18, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (94, 0, '¿CONOCE EL NOMBRE DE AL MENOS UN REGIDOR DEL MUNICIPIO DE TORREÓN?', 'BOOLEAN');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (95, 0, '¿CUÁL ES EL NOMBRE DEL REGIDOR QUE CONOCE?', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (96, 0, '¿CUÁL ES EL NOMBRE DEL REGIDOR QUE CONOCE?', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (97, 19, '¿CUÁL ES EL NOMBRE DEL REGIDOR QUE CONOCE?', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (98, 20, '¿CUÁL ES EL NOMBRE DEL REGIDOR QUE CONOCE?', 'TEXT');
INSERT INTO webandpr_vvTjz1Bk.app_questions (id, survey_id, title, type) VALUES (99, 18, '¿CUÁL ES EL NOMBRE DEL REGIDOR QUE CONOCE?', 'TEXT');