INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (1, 'Noticias', 'noticias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (2, 'Blogroll', 'blogroll', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (3, 'INDICADORES', 'indicadores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (4, 'TORREÓN', 'torreon', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (5, 'Seguridad y Justicia | Torreón', 'tor-seguridad-y-justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (6, 'CPT-layout-injector', 'cpt-layout-injector', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (7, 'not_global', 'not_global', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (8, 'layout', 'layout', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (9, 'regular', 'regular', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (10, 'Buen Gobierno | Torreón', 'tor-buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (11, 'deuda municipal', 'deuda-municipal', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (12, 'Torreón', 'torreon', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (13, 'pasivo', 'pasivo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (14, 'endeudamiento', 'endeudamiento', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (15, 'per cápita', 'per-capita', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (16, 'intereses', 'intereses', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (17, 'bancos', 'bancos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (18, 'ingresos municipales', 'ingresos-municipales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (19, 'presupuesto', 'presupuesto', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (20, 'gasto ejercido', 'gasto-ejercido', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (21, 'inversión pública', 'inversion-publica', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (22, 'transparencia', 'transparencia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (23, 'población', 'poblacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (24, 'jefatura', 'jefatura', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (25, 'divorcio', 'divorcio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (26, 'vivienda', 'vivienda', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (27, 'carencias', 'carencias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (28, 'crédito para vivienda', 'credito-para-vivienda', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (29, 'crédito', 'credito', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (30, 'vehículos', 'vehiculos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (31, 'accidentes de tránsito', 'accidentes-de-transito', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (32, 'economía', 'economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (33, 'producción', 'produccion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (34, 'productividad', 'productividad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (35, '2014', '2014', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (36, 'empresas', 'empresas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (37, '2016', '2016', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (38, 'balanza comercial', 'balanza-comercial', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (39, 'importación', 'importacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (40, 'exportación', 'exportacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (41, 'inflación', 'inflacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (42, 'rezago educativo', 'rezago-educativo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (43, 'años de estudio', 'anos-de-estudio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (44, 'Prueba Planea', 'prueba-planea', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (45, 'Economía | Torreón', 'tor-economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (46, 'Educación | Torreón', 'tor-educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (47, 'Desarrollo Urbano | Torreón', 'tor-desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (48, 'Empleo | Torreón', 'tor-empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (49, 'Medio Ambiente | Torreón', 'tor-medio-ambiente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (50, 'Participación Ciudadana | Torreón', 'tor-participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (51, 'Salud | Torreón', 'tor-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (52, 'empleo', 'empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (53, 'IMSS', 'imss', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (54, 'salario', 'salario', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (55, 'GÓMEZ PALACIO', 'gomez-palacio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (59, 'residuos', 'residuos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (60, 'agua', 'agua', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (61, 'contaminación', 'contaminacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (62, 'abstencionismo', 'abstencionismo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (63, 'votaciones', 'votaciones', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (64, 'organizaciones civiles', 'organizaciones-civiles', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (65, 'salud', 'salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (66, 'mortalidad', 'mortalidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (67, 'recursos', 'recursos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (68, 'competitividad', 'competitividad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (69, 'homicidios dolosos', 'homicidios-dolosos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (70, 'robo de vehículos', 'robo-de-vehiculos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (71, 'robo', 'robo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (72, 'robo casa habitación', 'robo-casa-habitacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (73, 'robo negocio', 'robo-negocio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (74, 'confianza en autoridades', 'confianza-en-autoridades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (75, 'seguridad pública', 'seguridad-publica', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (76, 'Personas extraviadas y desaparecidas en Torreón', 'personas-extraviadas-y-desaparecidas-en-torreon', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (77, 'desaparecidos', 'desaparecidos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (78, 'Gómez Palacio', 'gomez-palacio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (79, 'Buen Gobierno | Gómez Palacio', 'gp-buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (80, 'Desarrollo Urbano | Gómez Palacio', 'gp-desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (81, 'Economía | Gómez Palacio', 'gp-economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (82, 'Educación | Gómez Palacio', 'gp-educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (83, 'Empleo | Gómez Palacio', 'gp-empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (84, 'Medio Ambiente | Gómez Palacio', 'gp-medio-ambiente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (85, 'Participación Ciudadana | Gómez Palacio', 'gp-participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (86, 'Salud | Gómez Palacio', 'gp-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (87, 'Seguridad y Justicia | Gómez Palacio', 'gp-seguridad-y-justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (88, 'escolaridad', 'escolaridad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (89, 'educación pública', 'educacion-publica', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (90, 'calidad', 'calidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (91, 'residuos sólidos', 'residuos-solidos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (92, 'basura', 'basura', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (93, 'sector económico', 'sector-economico', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (94, 'elecciones', 'elecciones', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (95, 'organizaciones', 'organizaciones', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (96, 'sociedad civil', 'sociedad-civil', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (97, 'recursos para salud', 'recursos-para-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (98, 'cobertura de salud', 'cobertura-de-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (99, 'mortalidad infantil', 'mortalidad-infantil', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (100, 'percepción', 'percepcion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (101, 'inseguridad', 'inseguridad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (102, 'homicidios', 'homicidios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (103, 'ejército', 'ejercito', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (104, 'policía', 'policia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (105, 'extraviados', 'extraviados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (106, 'COAHUILA', 'coahuila-indicadores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (107, 'Buen Gobierno | Coahuila', 'coah-buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (108, 'Desarrollo Urbano | Coahuila', 'coah-desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (109, 'Economía | Coahuila', 'coah-economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (110, 'Educación | Coahuila', 'coah-educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (111, 'Empleo | Coahuila', 'coah-empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (112, 'Medio Ambiente | Coahuila', 'coah-medio-ambiente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (113, 'Participación Ciudadana | Coahuila', 'coah-participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (114, 'Salud | Coahuila', 'coah-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (115, 'Seguridad y Justicia | Coahuila', 'coah-seguridad-y-justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (116, 'deuda', 'deuda', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (117, 'deuda per cápita', 'deuda-per-capita', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (118, 'deuda pública', 'deuda-publica', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (119, 'pib', 'pib', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (120, 'interés', 'interes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (121, 'financiamiento', 'financiamiento', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (122, 'ingresos', 'ingresos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (123, 'ingresos estatales', 'ingresos-estatales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (124, 'aportaciones', 'aportaciones', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (125, 'inversión', 'inversion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (126, 'servicios personales', 'servicios-personales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (127, 'gasto', 'gasto', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (128, 'subsidios', 'subsidios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (129, 'imco', 'imco', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (130, 'crecimiento poblacional', 'crecimiento-poblacional', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (131, 'hogar', 'hogar', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (132, 'matrimonio', 'matrimonio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (133, 'hijos', 'hijos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (134, 'rezago', 'rezago', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (135, 'costo', 'costo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (136, 'infonavit', 'infonavit', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (137, 'accidentes', 'accidentes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (138, 'alcohol', 'alcohol', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (139, 'automóviles', 'automoviles', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (140, 'trabajadores', 'trabajadores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (141, 'comercio', 'comercio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (142, 'extranjero', 'extranjero', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (143, 'industria', 'industria', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (144, 'inversión extranjera', 'inversion-extranjera', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (145, 'crecimiento', 'crecimiento', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (146, 'crecimiento económico', 'crecimiento-economico', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (147, 'desempleo', 'desempleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (148, 'asegurados', 'asegurados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (149, 'informalidad', 'informalidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (150, 'formalidad', 'formalidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (151, 'tasa de desempleo', 'tasa-de-desempleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (152, 'partidos', 'partidos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (153, 'democracia', 'democracia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (154, 'voto', 'voto', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (155, 'sociedad', 'sociedad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (156, 'suicidio', 'suicidio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (157, 'policías', 'policias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (158, 'policías preventivos', 'policias-preventivos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (159, 'policías estatales', 'policias-estatales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (160, 'policías municipales', 'policias-municipales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (161, 'impunidad', 'impunidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (162, 'penitenciaría', 'penitenciaria', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (163, 'ceresos', 'ceresos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (164, 'ceferesos', 'ceferesos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (165, 'jóvenes', 'jovenes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (166, 'niños', 'ninos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (167, 'DURANGO', 'durango-indicadores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (168, 'Buen Gobierno | Durango', 'dgo-buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (169, 'Desarrollo Urbano | Durango', 'dgo-desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (170, 'Economía | Durango', 'dgo-economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (171, 'Educación | Durango', 'dgo-educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (172, 'Empleo | Durango', 'dgo-empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (173, 'Medio Ambiente | Durango', 'dgo-medio-ambiente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (174, 'Participación Ciudadana | Durango', 'dgo-participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (175, 'Salud | Durango', 'dgo-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (176, 'Seguridad y Justicia | Durango', 'dgo-seguridad-y-justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (177, 'LERDO', 'lerdo-indicadores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (178, 'Buen Gobierno | Lerdo', 'lerdo-buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (179, 'Desarrollo Urbano | Lerdo', 'lerdo-desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (180, 'Economía | Lerdo', 'lerdo-economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (181, 'Educación | Lerdo', 'lerdo-educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (182, 'Empleo | Lerdo', 'lerdo-empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (183, 'Medio Ambiente | Lerdo', 'lerdo-medio-ambiente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (184, 'Participación Ciudadana | Lerdo', 'lerdo-participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (185, 'Salud | Lerdo', 'lerdo-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (186, 'Seguridad y Justicia | Lerdo', 'lerdo-seguridad-y-justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (187, 'calidad del agua', 'calidad-del-agua', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (188, 'menu_principal', 'menu_principal', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (189, 'CPT-layout-taxonomy', 'cpt-layout-taxonomy', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (190, 'menu_secciones', 'menu_secciones', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (191, 'global', 'global', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (192, 'globales', 'globales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (193, 'section', 'section', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (194, 'menu_secundario', 'menu_secundario', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (195, 'PERCEPCIÓN', 'percepcion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (196, 'Edición diciembre 2016', 'edicion-diciembre-2016', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (197, 'Edición junio 2017', 'edicion-junio-2017', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (198, 'Buen Gobierno | Diciembre 2016', 'dic16-buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (199, 'Desarrollo Urbano | Diciembre 2016', 'dic16-desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (200, 'Economía | Diciembre 2016', 'dic16-economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (201, 'Educación | Diciembre 2016', 'dic16-educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (202, 'Empleo | Diciembre 2016', 'dic16-empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (203, 'Medio Ambiente | Diciembre 2016', 'dic16-medio-ambiente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (204, 'Participación Ciudadana | Diciembre 2016', 'dic16-participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (205, 'Salud | Diciembre 2016', 'dic16-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (206, 'Seguridad y Justicia | Diciembre 2016', 'dic16-seguridad-y-justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (207, 'Servicios Públicos | Diciembre 2016', 'dic16-servicios-publicos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (208, 'Buen Gobierno | Junio 2017', 'jun17-buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (209, 'Desarrollo Urbano | Junio 2017', 'jun17-desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (210, 'Economía | Junio 2017', 'jun17-economia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (211, 'Educación | Junio 2017', 'jun17-educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (212, 'Empleo | Junio 2017', 'jun17-empleo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (213, 'Participación Ciudadana | Junio 2017', 'jun17-participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (214, 'Salud | Junio 2017', 'jun17-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (215, 'Seguridad y Justicia | Junio 2017', 'jun17-seguridad-y-justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (216, 'Servicios Públicos | Junio 2017', 'jun17-servicios-publicos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (217, 'calificación', 'calificacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (218, 'autoridades', 'autoridades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (219, 'corrupción', 'corrupcion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (220, 'seguridad', 'seguridad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (221, 'transporte', 'transporte', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (222, 'emigrar', 'emigrar', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (223, 'ingreso', 'ingreso', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (224, 'educación', 'educacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (225, 'estudiantes', 'estudiantes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (226, 'drogadicción', 'drogadiccion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (227, 'sueldo', 'sueldo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (228, 'trabajo', 'trabajo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (229, 'aire', 'aire', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (230, 'limpieza', 'limpieza', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (231, 'votación', 'votacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (232, 'regidores', 'regidores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (233, 'asociación', 'asociacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (234, 'grupo', 'grupo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (235, 'participación', 'participacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (236, 'servicios', 'servicios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (237, 'delitos', 'delitos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (238, 'extorsión', 'extorsion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (239, 'denuncia', 'denuncia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (240, 'agua potable', 'agua-potable', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (241, 'alumbrado', 'alumbrado', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (242, 'pavimento', 'pavimento', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (243, 'vialidades', 'vialidades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (244, 'servicio público', 'servicio-publico', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (245, 'buen gobierno', 'buen-gobierno', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (246, 'medio de transporte', 'medio-de-transporte', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (247, 'familia', 'familia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (248, 'escuela', 'escuela', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (249, 'droga', 'droga', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (250, 'delito', 'delito', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (251, 'alumbrado público', 'alumbrado-publico', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (252, 'recolección de basura', 'recoleccion-de-basura', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (253, 'transporte público', 'transporte-publico', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (254, 'vialidad', 'vialidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (255, 'module', 'module', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (256, 'menu_indicadores', 'menu_indicadores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (257, 'SLICK', 'slick', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (258, 'Torreón', 'torreon', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (259, 'Gómez Palacio', 'gomez', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (260, 'Lerdo', 'lerdo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (261, 'Durango', 'durango', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (262, 'Coahuila', 'coahuila', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (263, 'Entidades', 'entidades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (264, 'Videos', 'videos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (265, 'post-format-video', 'post-format-video', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (266, 'logotipos', 'logotipos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (267, 'Percepción 2016', 'percepcion-2016', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (268, 'Percepción 2017', 'percepcion-2017', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (269, 'federación', 'federacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (270, 'pago', 'pago', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (271, 'administración', 'administracion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (272, 'deuda total', 'deuda-total', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (273, 'cierre', 'cierre', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (274, 'municipio', 'municipio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (275, 'burocracia', 'burocracia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (276, 'pública', 'publica', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (277, 'personales', 'personales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (278, 'redujo', 'redujo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (279, 'aprobado', 'aprobado', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (280, 'gastado', 'gastado', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (281, 'propios', 'propios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (282, 'estado', 'estado', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (283, 'coahuila', 'coahuila', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (284, 'promedio', 'promedio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (285, 'estados', 'estados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (286, 'país', 'pais', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (287, 'liquidar', 'liquidar', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (288, 'coahuilenses', 'coahuilenses', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (289, 'durango', 'durango', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (290, 'incremento', 'incremento', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (291, 'total', 'total', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (292, 'durangueses', 'durangueses', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (293, 'establecimientos', 'establecimientos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (294, 'manufacturas', 'manufacturas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (295, 'nacional', 'nacional', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (296, 'industrias', 'industrias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (297, 'manufactureras', 'manufactureras', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (298, 'maquinaria', 'maquinaria', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (299, 'equipo', 'equipo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (300, 'ied', 'ied', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (301, 'industrias manufactureras', 'industrias-manufactureras', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (302, 'exportaciones', 'exportaciones', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (303, 'actividades', 'actividades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (304, 'manufacturera', 'manufacturera', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (305, 'tasa', 'tasa', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (306, 'sector', 'sector', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (307, 'estatal', 'estatal', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (308, 'inmobiliarios', 'inmobiliarios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (309, 'alquiler', 'alquiler', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (310, 'energía', 'energia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (311, 'fuga', 'fuga', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (312, 'capital', 'capital', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (313, 'mayores', 'mayores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (314, 'económicas', 'economicas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (315, 'económico', 'economico', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (316, 'nuevas', 'nuevas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (317, 'ciudad', 'ciudad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (318, 'bienes', 'bienes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (319, 'sector servicios', 'sector-servicios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (320, 'lerdo', 'lerdo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (321, 'empleos', 'empleos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (322, 'formales', 'formales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (323, 'secundarias', 'secundarias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (324, 'salarios', 'salarios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (325, 'cifra', 'cifra', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (326, 'ganan', 'ganan', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (327, 'laboran', 'laboran', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (328, 'nuevos', 'nuevos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (329, 'generaron', 'generaron', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (330, 'mínimos', 'minimos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (331, 'menos', 'menos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (332, 'perdieron', 'perdieron', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (333, 'económicamente', 'economicamente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (334, 'activa', 'activa', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (335, 'desocupada', 'desocupada', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (336, 'desempleados', 'desempleados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (337, 'estudios', 'estudios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (338, 'técnicos', 'tecnicos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (339, 'profesionales', 'profesionales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (340, 'Los Medios', 'los-medios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (341, 'post-format-link', 'post-format-link', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (342, 'Vídeo', 'video', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (343, 'Media superior', 'media-superior', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (344, 'Escuelas', 'escuelas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (345, 'Alumnos', 'alumnos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (346, 'eduación básica', 'eduacion-basica', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (347, 'Universidad', 'universidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (348, 'egresados', 'egresados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (349, 'Universidades', 'universidades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (350, 'estuduiantes', 'estuduiantes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (351, 'Carreras Unuversitarias', 'carreras-unuversitarias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (352, 'carreras universitarias', 'carreras-universitarias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (353, 'Así Vivimos', 'asi-vivimos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (354, 'congresos', 'congresos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (355, 'Embarazos', 'embarazos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (356, 'nacimientos', 'nacimientos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (357, 'adolescentes', 'adolescentes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (358, 'diabetes', 'diabetes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (359, 'corazón', 'corazon', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (360, 'cáncer', 'cancer', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (361, 'Suicidios', 'suicidios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (362, 'Embarazos en Adolescentes', 'embarazos-en-adolescentes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (363, 'natalidad', 'natalidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (364, 'simas', 'simas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (365, 'PUBLICACIONES', 'publicaciones', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (366, 'Finanzas de Coahuila', 'finanzas-de-coahuila', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (367, 'Finanzas de Durango', 'finanzas-de-durango', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (368, 'loop', 'loop', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (369, 'cpt-LOOPS', 'cpt-loops', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (370, 'segurida', 'segurida', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (371, 'percepción social', 'percepcion-social', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (372, 'victimización', 'victimizacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (373, 'obesidad', 'obesidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (374, 'Laguneros', 'laguneros', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (375, 'Edición Octubre 2018', 'edicion-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (376, 'Buen Gobierno | Octubre 2018', 'buen-gobierno-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (377, 'Desarrollo Urbano | Octubre 2018', 'desarrollo-urbano-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (378, 'Economía| Octubre 2018', 'economia-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (379, 'Educación| Octubre 2018', 'educacion-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (380, 'Empleo | Octubre 2018', 'empleo-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (381, 'Participación Ciudadana | Octubre 2018', 'participacion-ciudadana-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (382, 'Medio Ambiente | Octubre 2018', 'medio-ambiente-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (383, 'Salud | Octubre 2018', 'salud-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (384, 'Seguridad y Justicia | Octubre 2018', 'seguridad-y-justicia-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (385, 'Servicios Públicos | Octubre 2018', 'servicios-publicos-octubre-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (386, 'servicios públicos', 'servicios-publicos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (387, 'drenaje', 'drenaje', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (388, 'trasporte', 'trasporte', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (389, 'servicio', 'servicio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (390, 'regular', 'regular', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (391, 'abandonaría', 'abandonaria', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (392, 'fuera de la ciudad', 'fuera-de-la-ciudad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (393, 'antigüedad', 'antiguedad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (394, 'laboral', 'laboral', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (395, 'participación ciudadana', 'participacion-ciudadana', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (396, 'votar', 'votar', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (397, 'afiliación', 'afiliacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (398, 'Seguro Popular', 'seguro-popular', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (399, 'servicio de salud', 'servicio-de-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (400, 'familias', 'familias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (401, 'dificultades', 'dificultades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (402, 'delito mas frecuente', 'delito-mas-frecuente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (403, 'secuestro', 'secuestro', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (404, 'robo a casa habitación', 'robo-a-casa-habitacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (405, 'robo a negocio', 'robo-a-negocio', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (406, 'asalto en la calle', 'asalto-en-la-calle', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (407, 'camion', 'camion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (408, 'caminando', 'caminando', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (409, 'automóvil', 'automovil', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (410, 'Robo en casa', 'robo-en-casa', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (411, 'robo en la calle', 'robo-en-la-calle', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (412, 'delitos frecuentes', 'delitos-frecuentes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (413, 'alcaldes', 'alcaldes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (414, 'gobernador', 'gobernador', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (415, 'presidente', 'presidente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (416, 'abandonaría la ciudad', 'abandonaria-la-ciudad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (417, 'desarrollo urbano', 'desarrollo-urbano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (418, 'ciudadanos', 'ciudadanos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (419, 'mejor futuro', 'mejor-futuro', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (420, 'evaluación', 'evaluacion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (421, 'municipales', 'municipales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (422, 'motivo para irse', 'motivo-para-irse', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (423, 'irse de la ciudad', 'irse-de-la-ciudad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (424, 'denuncias', 'denuncias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (425, 'desconfianza', 'desconfianza', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (426, 'tramites', 'tramites', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (427, 'perdida de tiempo', 'perdida-de-tiempo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (428, 'asociación civil', 'asociacion-civil', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (429, 'grupo ciudadano', 'grupo-ciudadano', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (430, 'corrupción autoridades', 'corrupcion-autoridades', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (431, 'abandonarían la ciudad', 'abandonarian-la-ciudad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (432, 'rango de edad', 'rango-de-edad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (433, 'ciudadanía', 'ciudadania', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (434, 'pobreza', 'pobreza', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (435, 'aumento de precios', 'aumento-de-precios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (436, 'escases de agua', 'escases-de-agua', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (437, 'problemas', 'problemas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (438, 'problemáticas económicas', 'problematicas-economicas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (439, 'seguro', 'seguro', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (440, 'electorales', 'electorales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (441, 'Saludo', 'saludo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (442, 'servicios de salud', 'servicios-de-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (443, 'centro de salud', 'centro-de-salud', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (444, 'no alcanza', 'no-alcanza', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (445, 'no ocurrió nada', 'no-ocurrio-nada', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (446, 'venta de drogas', 'venta-de-drogas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (447, 'medio ambiente', 'medio-ambiente', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (448, 'contaminación aire', 'contaminacion-aire', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (449, 'sucia', 'sucia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (450, 'jardines', 'jardines', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (451, 'parques', 'parques', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (452, 'suciedad', 'suciedad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (453, 'Felices', 'felices', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (454, 'como se consideran', 'como-se-consideran', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (455, 'partidos políticos', 'partidos-politicos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (456, 'Ministerios Públicos', 'ministerios-publicos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (457, 'creer', 'creer', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (458, 'políticos', 'politicos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (459, 'insatisfecho', 'insatisfecho', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (460, 'medicamento', 'medicamento', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (461, 'disponibilidad', 'disponibilidad', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (462, 'mejorará', 'mejorara', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (463, 'confianza', 'confianza', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (464, 'marina', 'marina', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (465, 'puntaje', 'puntaje', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (466, 'Confían', 'confian', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (467, 'megadeuda', 'megadeuda', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (468, 'ENSU', 'ensu', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (469, 'RESPALDOS', 'respaldos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (470, 'row', 'row', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (471, 'Columnas', 'columnas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (472, 'muertes', 'muertes', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (473, 'madres', 'madres', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (474, 'mueren', 'mueren', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (475, 'instituciones públicas', 'instituciones-publicas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (476, 'divorcios', 'divorcios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (477, 'casados', 'casados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (478, 'parejas', 'parejas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (479, 'Primaria', 'primaria', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (480, 'secundaria', 'secundaria', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (481, 'clases', 'clases', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (482, 'escolar', 'escolar', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (483, 'educacion', 'educacion-2', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (484, 'educación básica', 'educacion-basica', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (485, 'educación media', 'educacion-media', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (486, 'resultado', 'resultado', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (487, 'matemáticas', 'matematicas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (488, 'reprueban', 'reprueban', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (489, 'PLANEA', 'planea', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (490, 'Gasto público', 'gasto-publico', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (491, 'INGRESOS FEDERALES', 'ingresos-federales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (492, 'Ingresos propios', 'ingresos-propios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (493, 'deudas', 'deudas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (494, 'deudas con bancos', 'deudas-con-bancos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (495, 'deudas municipales', 'deudas-municipales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (496, 'gasto aprobado', 'gasto-aprobado', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (497, 'rubros', 'rubros', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (498, 'deuda contratada', 'deuda-contratada', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (499, 'deuda con bancos', 'deuda-con-bancos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (500, 'deuda proveedores', 'deuda-proveedores', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (501, 'aportaciones federales', 'aportaciones-federales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (502, 'participaciones federales', 'participaciones-federales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (503, 'recursos federales asignados', 'recursos-federales-asignados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (504, 'deuda estatal', 'deuda-estatal', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (505, 'deuda durango', 'deuda-durango', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (506, 'pago total', 'pago-total', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (507, 'minería', 'mineria', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (508, 'producto interno bruto', 'producto-interno-bruto', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (509, 'nuevas empresas', 'nuevas-empresas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (510, 'empresas en lerdo', 'empresas-en-lerdo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (511, 'nuevas empresa', 'nuevas-empresa', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (512, 'trabajadores asegurados', 'trabajadores-asegurados', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (513, 'Rango salarial', 'rango-salarial', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (514, 'PIB nacional', 'pib-nacional', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (515, 'diputados federales', 'diputados-federales', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (516, 'financiamiento a partidos', 'financiamiento-a-partidos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (517, 'electoral', 'electoral', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (518, 'votos', 'votos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (519, 'financiamientos a partidos', 'financiamientos-a-partidos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (520, 'ejercieron votos', 'ejercieron-votos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (521, 'ejercieron su voto', 'ejercieron-su-voto', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (522, 'tineladas', 'tineladas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (523, 'indicadores_torreon', 'indicadores_torreon', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (524, 'Percepción 2018', 'percepcion-2018', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (525, 'Infografías', 'infografias', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (526, 'autos', 'autos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (527, 'metrobús', 'metrobus', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (528, 'robo vehiculos', 'robo-vehiculos', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (529, 'desaceleración', 'desaceleracion', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (530, 'feminicidios', 'feminicidios', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (531, 'violencia', 'violencia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (532, 'justicia', 'justicia', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (533, 'cabildo', 'cabildo', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (534, 'Villa Unión', 'villa-union', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (535, 'finanzas', 'finanzas', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (536, 'México Evalúa', 'mexico-evalua', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (537, 'IEC', 'iec', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (538, 'Coronavirus', 'coronavirus', 0);
INSERT INTO webandpr_vvTjz1Bk.w47fa_terms (term_id, name, slug, term_group) VALUES (539, 'Covid-19', 'covid-19', 0);